### ISSUE TITLE
Hi, kuhanmo

### ISSUE THREAD

**Issue by taeguk** [kuhanmo/Python_study#1]
hey, what book do you use?

**Comment by taeguk** [comment]
let's study with me and other drawml homies!

**Comment by kuhanmo** [comment]
Thanks a lot taeguk!!!
I wanna study with you but,  you dont' here 
please come to membership

**Comment by taeguk** [comment]
Okay man, I will go membership tomorrow for both algorithm lecture and DrawML meeting.
Let's discuss about our future for DrawML tomorrow.
Admit? Yes I admit!
