### ISSUE TITLE
Hey, check your email config.

### ISSUE THREAD

**Issue by taeguk** [kuhanmo/Python_study#2]
Your commit is not associated with your github account.
Check your email config please.
If you use linux shell, use ```git config```.
For detail, google it!

**Comment by kuhanmo** [comment]
Thanks, I will check my config before next commit!

**Comment by taeguk** [comment]
Good. After you solve this problem, close this issue please. :)

**Comment by taeguk** [comment]
Hey!! are you kidding me? Not bug fixed!!!!!
